# Maki template version: 1.0

version: '3.2'

volumes:
    db-data:

services:
  frontend:
    container_name: news_nginx
    build:
      context: .
      dockerfile: .deploy/docker/nginx/Dockerfile
    volumes:
      - ./.deploy/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - backend
    ports:
      - 8088:80

  backend:
    container_name: news_php-fpm
    build:
      context: .
      dockerfile: .deploy/docker/php_fpm/Dockerfile
    env_file:
        - ./.env
    volumes:
      - .:/app
  db:
      container_name: news_db
      image: postgres
      restart: always
      environment:
          POSTGRES_PASSWORD: root
          POSTGRES_DB: news_db
      volumes:
          - db-data:/var/lib/postgresql/data
